### PR TITLE
🐛 use cnspec as base image

### PR DESCRIPTION
**Pull request by joelddiaz**
now that mondoo binary calls out to cnspec, we need to ensure that cnspec is actually there to call to

### CODE REVIEW

**Comment by joelddiaz** [comment]
this of course assumes a 1-to-1 mondooVersion-to-cnspec-Version relationship...

**Comment by benr** [comment]
We want to expunge the mondoo binary.  So the entrypoint should be cnquery and all the installation steps are gone.

**Comment by joelddiaz** [comment]
i thought for compatability purposes we were keeping the mondoo container image with v7 behavior. the mondoo wrapper does do things like translate subcommands that were renamed in cnspec and translating parameters that were renamed as well (eg 'mondoo run local --query "platform"' becomes 'cnspec run local --command "platform"')

**Comment by benr** [comment]
Added new version.  I'd like @chris-rock to validate before merge.

```
$ docker run -ti mondoo/client:8.0.0 version
cnquery 8.0.0 (a3f56da5, 2023-03-09T18:51:57Z)
```

**Comment by benr** [comment]
@joelddiaz Give me one more check and lets merge.

**Comment by chris-rock** [comment]
@joelddiaz this is covered with command aliases in cnspec. The old commands should still work. If something is missing we can add command aliases to cnspec

**Comment by chris-rock** [comment]
I think building it on top of cnspec makes sense. This container is deprecated. Going forward users should use mondoo/cnspec directly

**Pull request merged**
